### ISSUE TITLE
Problem with hooks/pluginDir with 1.0.2

### ISSUE THREAD

**Issue by fufroma** [DE-IBH/apt-dater#100]
Hello,

I had a problem with apt-dater.xml with my upgrade 1.0.1 -> 1.0.2 .

I have a specific pluginDir option in <hooks /> and the option does not exist in the dtd.
`element hooks: validity error : No declaration for attribute pluginDir of element hooks`

(And the documentation in the configuration does not match the example the line after: one say pluginDir, the other plugin-dir.)

So, I suggest : 
  * rename pluginDir to plugin-dir in apt-dater.xml
  * add `<!ATTLIST hooks plugin-dir CDATA #IMPLIED>` in apt-dater.dtd , in the `hooks` sections

With those modification, everything work fine.

**Comment by dkadioglu** [comment]
Hi,

+1 for that fix. One question: Do hooks actually work for you? Using the most recent code the hooks don't work at all. Just asking so I can decide if I should open a new issue or not.
Thanks.

**Comment by fodor99** [comment]
Hi,

Hooks with 1.0.2 not working for me. Do You know which is the latest version that has working hooks?
Thanks.

**Comment by dkadioglu** [comment]
Hooks are working for me now...wrong permissions *sigh*
Sorry for the alert.

**Comment by liske** [comment]
I've fixed the example and added the attribute definition of `plugin-dir` to the schema file. Thanks!
