### ISSUE TITLE
make install ignores --sysconfdir

### ISSUE THREAD

**Issue by dunn** [DE-IBH/apt-dater#101]
make always attempts to install conf files in `/etc`, which means `make install` can't be run without `sudo`.

Build logs with system config: https://gist.github.com/dunn/d8a7a27ea04cfa78f1b6#file-03-make-L126

Presumably introduced by 1f165f4ea7e4437dc87bca31de654c160a90c1e7.

**Comment by liske** [comment]
Hi,

I've changed `/etc/Makefile.am` to use *@sysconfdir@* in ba81bcd . The default configuration files are now using the value of *sysconfdir* in the path options, too.

Thanks & HTH,
Thomas
