### ISSUE TITLE
Server HostName

### ISSUE THREAD

**Issue by moonmeister** [DE-IBH/apt-dater#106]
We don't run DNS for local server names so I enter them in by IP in the hosts file. The downside of this is I have to remember servers my their IP not a descriptive name. As part of the Host details can apt-dater pull back the Hostname and then in the menu system reference the server by the hostname not the IP/FQDN located in the hosts file? Thanks for all the good work on this app!

**Comment by liske** [comment]
Move the mapping into the stub resolver (`/etc/hosts`) or into ssh's configuration (`Host` statement in `~/.ssh/config` or `/etc/ssh/ssh_config`). It is possible to specify the ip or portnumber within apt-dater's hosts file... but it might be more reasonable to make the mapping available outside of apt-dater.
