### ISSUE TITLE
ssh multihop support

### ISSUE THREAD

**Issue by jlherren** [DE-IBH/apt-dater#108]
I have a few Debian hosts that aren't reachable using ssh directly, therefore I use the SSH multihop technique to log into them (i.e. I proxy through a different server). There are several ways to achieve this. My local **.ssh/config** file contains this:

```
Host target
        ProxyCommand ssh -q -i ~/some-key-file someuser@proxy.example.com
```

proxy.example.com's **.ssh/authorized_keys** file contains this:

`
command="nc target 22",<other options omitted> ssh-rsa <key-omitted>
`

This allows me to just type `ssh user@target` and it let's me log into the target. I can also do `ssh user@target command` and similar things (which is what I assume apt-dater is doing).

However I'm unable to reach that target machine using apt-dater. Whenever I try to 'c'onnect I get this line:

`
-bash: line 1: $'SSH-2.0-OpenSSH_7.1p2-hpn14v10\r': command not found
`

Has anyone successfully used apt-dater with multihop ssh?

**Comment by liske** [comment]
This is not apt-dater related. You need to add multiple Host statements at your origin host:

```
Host final.target
    ProxyCommand ... intermediate.target

Host intermediate.target
    ProxyCommand ... first.hop
```

**Comment by jlherren** [comment]
I'm not sure what you mean... SSH to the target already works great, so the SSH config seems okay. I don't understand the second half of your config, is that supposed to be on the proxy host?

**Comment by liske** [comment]
The ssh config is only on the first host. The ssh client is doing recursive lookups:
- to reach the final host, use the intermediate as a proxy
- to reach the intermediate, use the first as a proxy

**Comment by jlherren** [comment]
I still don't understand, but it seems you're trying to do one hop more than I actually need. There's no "first.hop" in my setup. In any case, my SSH config is already working perfectly fine. I'll try to dig into the code and see why it's not working, it seems apt-dater connects to the wrong ssh process (since there are two being spawned). Thanks anyway.

**Comment by jlherren** [comment]
I found out that using the SSH agent screws things up. If I don't use <ssh spawn-agent="true"> in the apt-dater config, then everything works fine and I can connect to my hosts. I'll just stop using the agent for now.

**Comment by jlherren** [comment]
Okay, sorry for the noise. I figured it out.

The proxy command was completely and silently ignoring my '-i <key>' option, since a valid key for that host was already loaded via ssh-agent. Since that is the wrong key in my situation, this screwed things up. The proxy command needs to ignore the agent. My new .ssh/config looks like this and everything works fine:

```
Host target
        ProxyCommand ssh -q -i ~/some-key-file -o "IdentitiesOnly yes" someuser@proxy.example.com
```
