### ISSUE TITLE
Generated /etc files have ${prefix} in them

### ISSUE THREAD

**Issue by kpengboy** [DE-IBH/apt-dater#112]
After running `./configure`, the files `etc/hosts.xml` and `etc/apt-dater.xml` have the lines

    <!DOCTYPE hosts SYSTEM "file://${prefix}/share/xml/schema/apt-dater/hosts.dtd">

and

    <!DOCTYPE apt-dater SYSTEM "file://${prefix}/share/xml/schema/apt-dater/apt-dater.dtd">

respectively in them. Here, the string `${prefix}` should be substituted out, but isn't. This issue persists when the files are installed, and results in apt-dater not launching correctly on first run because the paths in the lines above aren't valid.

**Comment by phaidros7** [comment]
Same issue here.

**Comment by liske** [comment]
The path was build using DATAROOTDIR which was not recursive evaled - fixed.
