### ISSUE TITLE
ADPERR: Error executing 'sudo yum list updates' (256)

### ISSUE THREAD

**Issue by ehrenwert-it** [DE-IBH/apt-dater#114]
Hello,

I freshly configured apt-dater. Now I'd like to connect to a host to perform update-operations.

This is the error-report I'm getting if I refresh the host with `g`-key and using `e`-key to display errors:

```
Pseudo-terminal will not be allocated because stdin is not a terminal.
ADPROTO: 0.7
LSBREL: CentOS|7.2.1511|Core
VIRT: Unknown
UNAME: Linux|x86_64
FORBID: 0
sudo: sorry, you must have a tty to run sudo

ADPERR: Error executing 'sudo yum list updates' (256).

```

If I press `c` I can connect to host without problems and I'm allowed to run `sudo yum list updates`:

```
[apt-dater@1 ~]$ sudo yum list updates
Geladene Plugins: fastestmirror
Loading mirror speeds from cached hostile
 * base: mirror.imt-systems.com
 * epel: mirror.imt-systems.com
 * extras: ftp.hosteurope.de
 * updates: mirror.eu.oneandone.net

```

Any ideas how to solve the problem?

**Comment by liske** [comment]
Hi,

this is a problem of your sudo configuration sudoers(5):

```
sudo: sorry, you must have a tty to run sudo
```

You need to allow `apt-dater-host` to run yum w/o a allocated TTY (option _requiretty_).


HTH,
Thomas
