### ISSUE TITLE
Detect binaries from PATH

### ISSUE THREAD

**Issue by enko** [DE-IBH/apt-dater#115]
I'm trying to get apt-dater running on [NixOS](https://nixos.org/) but I'm hitting some limits. One for example is that in NixOS binaries usualy are not inside /usr/bin but somewhere else and mostly in $PATH. For example ssh is in /run/current-system/sw/bin/ssh and screen is in /home/tim/.nix-profile/bin/screen. Both files are symlinks to other paths.

It would recommend that if not configured in the respective ssh, screen or tmux tag, apt-dater should check PATH and then fall back to the hard coded SCREEN_BINARY constant.

**Comment by liske** [comment]
I'm not going to add code to apt-dater to search in path or spawn sub shells just to start binaries normally installed at well-known paths (read: violating [FHS](http://refspecs.linuxfoundation.org/fhs.shtml)).

Regards,
Thomas
