### ISSUE TITLE
Debian 8 doesn't display current Kernel version in listing.

### ISSUE THREAD

**Issue by Tyrewt** [DE-IBH/apt-dater#121]
Running Apt-Dater 0.9.0-3+wheezy1 on Debian 7. Within the host listing, Debian 8 servers do not show current Kernel version and display as "**Debian 8.5 jessie; Linux**", where as Debian 7 shows current Kernel version "**Debian 7.11 wheezy; 3.2.0-4-amd64**".

Potential bug?

**Comment by liske** [comment]
Could you please show the output of `apt-dater-host status` on the affected jessie host run as the same user you are using in *apt-dater*? The last line should be `KERNELINFO: ` showing the current kernel version.

**Comment by Tyrewt** [comment]
KERNELINFO: 0 3.16.0-4-amd64

Note: Most likely doesn't make a difference, but that command required sudo. My UID in apt-dater used to access all systems has the password disabled (passwd --lock).  So I control + C out of the sudo prompt and information you requested displayed.

**Comment by Tyrewt** [comment]
Has this been identified as an issue?

**Comment by Tyrewt** [comment]
Status update?

**Comment by liske** [comment]
You must not get a sudo query If you run `apt-dater-host status` as the same user as from *apt-dater*. Since I'm not able to reproduce this issue it might be just a missing sudoers configuration (take a look at /etc/sudoers.d/apt-dater).

**Comment by Tyrewt** [comment]
Keep in mind this works with Debian 7/Cent OS 6. My apt-dater user has the following in sudoers configuration:

>ursername ALL=NOPASSWD: /usr/bin/apt-get, /usr/bin/aptitude

**Comment by Tyrewt** [comment]
Same issue with Debian 9. Can you please clarify how to troubleshoot or if more information is required from me. Thank you.

**Comment by liske** [comment]
Could you please check if your _sudoers_ does contain a `requiretty`? This would prevent `apt-dater-host status` to succeed if run non-interactive.

**Comment by Tyrewt** [comment]
I checked the /etc/sudoers config on a Debian 7, 8 and 9 host. None of them mention "requiretty", but as indicated in the initial bug report Debian 7 hosts display the Kernel version within Apt-Dater and Debian 8/9 do not.

**Comment by Tyrewt** [comment]
![apt-dater-error](https://user-images.githubusercontent.com/21961083/30454459-67b9015a-996a-11e7-9389-5b3402fce0b9.png)

Note in this screenshot, Debian 7 sows Kernel version, Debian 9 (outlined in red) does not.

**Comment by liske** [comment]
After reading the issue from the beginning I realized that I was maybe misdirected by the sudo stuff. Is it correct that you still running _apt-dater_ on _Wheezy_? Any machines running _Jessie+_ won't show kernel informations since there was a major change in apt-dater(-host) 1.0.0. Although _apt-dater_ should support older _apt-dater-host_ versions, the other way around is not supported.

**Comment by Tyrewt** [comment]
Apt-dater (0.9.0) is running on Debian 7. It's unfortunate this feature has been removed, was rather useful.

**Comment by liske** [comment]
The feature is still available but the implementation has changed. More recent versions of *apt-dater(-host)* use *needrestart* the get the current and available kernel versions.

**Comment by Tyrewt** [comment]
If I execute apt-dater-host status the Kernel version is displayed. However, I noticed only some hosts (Debian 9.11) in Apt-Dater are displaying the Kernel version. You mentioned _needrestart_ , but what should I be checking for?

**Comment by liske** [comment]
> 1. If I execute apt-dater-host status the Kernel version is displayed. However, I noticed only some hosts (Debian 9.11) in Apt-Dater are displaying the Kernel version. You mentioned _needrestart_ , but what should I be checking for?

You need to install the package. Since it is listed as *Recommends* in *apt-dater-host* it might get installed automaticaly.

> 2. It also appears that hosts built from Debian 9 work but upgraded hosts do not. Would the issue have something to do with hosts that have been upgraded from Debian 8 to Debian 9?

Could you check if *needrestart* might make the difference? As it is only recommended by *apt-dater-host* it might not get be installed while dist-upgrading.

> 3. Does this feature work with Debian 10 Buster?

It should work as in stretch.


Please use independend issue(s) for new problems or bugs.
