### ISSUE TITLE
Website down?

### ISSUE THREAD

**Issue by gregfr** [DE-IBH/apt-dater#123]
When clicking the link at the top of the readme file, I get a 404...

**Comment by fgeek** [comment]
Still down.

**Comment by candlerb** [comment]
Specifically this is the project description:

> terminal-based remote package update manager http://www.ibh.de/apt-dater/

**Comment by kallies** [comment]
AFAIK the URL got lost when ibh.de got redesigned. A lot of links point to this URL, so at least a redirect (e.g. to https://github.com/DE-IBH/apt-dater) should be added. Alternatively all links have to be changed.

**Comment by candlerb** [comment]
What's the new link?  Or is it just https://github.com/DE-IBH/apt-dater ?

**Comment by liske** [comment]
@kallies exactly - I need to fetch the lost page from the VCS and put it somewhere again.

**Comment by mathiashro** [comment]
Hello @gregfr, I've checked the different sources for apt-dater and apt-dater-host but did not found any non updated READMEs anymore. May be this issue can be closed / marked as resolved?

**Comment by ktosiek** [comment]
The link is still displayed in the "About" section on GitHub: https://github.com/DE-IBH/apt-dater

**Comment by liske** [comment]
I've just removed the link in the github profile :+1:
