### ISSUE TITLE
Please fix internal err-pattern default (regression from a82d3f7d4947c9dd100dd883d346239da7e96d83)

### ISSUE THREAD

**Issue by absurd34** [DE-IBH/apt-dater#124]
Hi,

in a82d3f7d4947c9dd100dd883d346239da7e96d83, err-pattern's hardcoded internal default
was changed and html entities introduced where they should not be.

This makes this feature fail for anyone not having a custom setting.

Please see

https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=827339

for more details (and the Debian patch for this).

Thx!

S

**Comment by liske** [comment]
Thanks!
