### ISSUE TITLE
travis: gettext version

### ISSUE THREAD

**Issue by kallies** [DE-IBH/apt-dater#139]
Travis CI fails with getext version issues.

Travis build example: https://travis-ci.org/DE-IBH/apt-dater/builds/289000719

Probably `AM_GNU_GETTEXT_VERSION([0.19.3])` needs to be bumped.

https://github.com/DE-IBH/apt-dater/blob/master/configure.ac#L23

**Comment by liske** [comment]
Sadly the Travis CI images are to old. I've changed the travis stuff to use a more recent Debian docker image for CI.
