### ISSUE TITLE
apt-dater does not use the default config file

### ISSUE THREAD

**Issue by mkleins** [DE-IBH/apt-dater#144]
##### ISSUE TYPE

 - Bug Report

##### APT-DATER VERSION

apt-dater 1.0.3

##### CONFIGURATION

Install with debian repositories

##### OS / ENVIRONMENT

Debian 9

##### SUMMARY

In fresh install, apt-dater create config files in /root/.config/apt-dater but don't use it !

##### STEPS TO REPRODUCE

* Install apt-dater with apt command
* Configure /root/.config/apt-dater/hosts.xml file
* Start apt-dater 

##### EXPECTED RESULTS

See hosts from hosts.xml file

##### ACTUAL RESULTS

See default host

**Comment by roykrikke** [comment]
Same here!

apt-dater -v
apt-dater 1.0.3 - Fri May 26 13:54:42 UTC 2017

cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 9 (stretch)"
NAME="Debian GNU/Linux"
VERSION_ID="9"
VERSION="9 (stretch)"
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"

**Comment by liske** [comment]
The default configuration (`$HOME/.config/apt-dater.xml`) includes the global configuration file `/etc/apt-dater/apt-dater.xml`. This default configuration uses global config files and directories, only:

```
    <paths
           hosts-file="/etc/apt-dater/hosts.xml"
           history-dir="/var/lib/apt-dater/history"
           stats-dir="/var/cache/apt-dater/stats"
           umask="007"/>
```

So you need to change your `$HOME/.config/apt-dater.xml` to *not* use the global configuration.

_Please do **not** run apt-dater as root!_
