### ISSUE TITLE
Errors after installation

### ISSUE THREAD

**Issue by MAGICCC** [DE-IBH/apt-dater#145]
Hi, 
Since I moved to Ubuntu with my apt-dater master I saw that the whole config files changed. But I get following errors after I installed it using `apt install apt-dater`

```
root@maguc:~/.config/apt-dater# apt-dater
validity error : Could not build URI for external subset "file://${prefix}/share/xml/schema/apt-dater/apt-dater.dtd"
Error on loading config file /root/.config/apt-dater/apt-dater.xml
```

**Comment by xxorax** [comment]
Confirmed on Ubuntu 16.04, v1.0.2+git20151216-1

Posted on https://bugs.launchpad.net/ubuntu/+source/apt-dater/+bug/1747925

To fix by hand, just replace ${prefix} by /usr in .config/apt-dater/apt-dater.xml and hosts.xml (don't forget the first / : `file://${prefix}` become `file:///usr` )

**Comment by MAGICCC** [comment]
Oh this is still open, forgot to closed it some weeks ago
