### ISSUE TITLE
"Pane is dead" appearing again without hint

### ISSUE THREAD

**Issue by tpo** [DE-IBH/apt-dater#146]
Hello,

I am seeing the same problem as in #90 - that is when a update terminates "Pane is dead" is shown. The "workaround" given in #90 - i.e. pressing "CTRL-a x" works.

As I understand it, commit 92474770a5b6423d6849d3383b0f78f434b24eef should have added a hint on how to terminate the session. However I am not seeing that hint - I only see a "Pane is dead" note on the bottom left of the screen and that's it.

My system here is Debian stretch with apt-dater 1.0.3-4.

**Comment by sathieu** [comment]
I'm having the same problem (Debian stretch with apt-dater 1.0.3-4 too)

**Comment by sathieu** [comment]
It looks like we need #130

**Comment by sathieu** [comment]
Any change to have 53886e55fc549 included in a stretch point-release?

**Comment by liske** [comment]
#130 was already merged so this issue should be already fixed.
