### ISSUE TITLE
Normal exit showed an error

### ISSUE THREAD

**Issue by 3Tri** [DE-IBH/apt-dater#150]
Hi!
I am using apt-dater 1.0.3 on Debian 9 with some Debian and Ubuntu VMs.
Some update runs showed "_An error at SERVERNAME has been detected [Less/ignore/connect]_"
But there was no error in output, just the some systemd ouput.

**Comment by liske** [comment]
Is it possible for you to provide the screen logs for a session where apt-dater claims there was an error?

**Comment by 3Tri** [comment]
I sas this today:

```
Scanning kernel images... [                                                                                                                                                                                  ]
^MScanning kernel images...                                                                                                                                                                                    
Failed to retrieve available kernel versions.
No services need to be restarted.
Connection to $SERVER closed.
```
This is a Xen-machine without /boot.

**Comment by liske** [comment]
You need to update all those files:
- `etc/...` + `conf/` => the global and user config
- `src/...` => the default value for the config parser
- `man/...` => the docbook source file (.xml.xml) and derived man page and html file

Please add patches for all files into your PR. Splitting up `fail` and `failed` for the negative lookahead seems to be a good idea.
