### ISSUE TITLE
Permission denied only on refresh (OSX)

### ISSUE THREAD

**Issue by drcursor** [DE-IBH/apt-dater#154]
apt-dater on osx (0.9.0) seems to be unable to execute it's refresh procedure and fails with the error "Failure diagnostic / Permission denied (publickey)".

- I'm able to connect to the hosts via apt-dater, install packages, etc.
- ssh root@remotehost apt-dater-host refresh  works without any issue
- On the remote hosts auth.log I get the only the following line "remotehost sshd[17235]: Connection closed by x.x.x.x port 54468 [preauth]"

Is there a way to attach to this failed session or somehow access a log ?

**Comment by mathiashro** [comment]
Hello @drcursor, may be the issue is already solved? I've tested 1.0.4 with macOS (via brew). The remote hosts are running different Debian versions.

**Comment by liske** [comment]
I'm going to close this old issue, looks like to be ssh but not apt-dater related at all. :thinking:
