### ISSUE TITLE
Cluster hanging

### ISSUE THREAD

**Issue by TB-archIT** [DE-IBH/apt-dater#155]
Hi,

using apt-dater for a long time. Thanks for this great tool!

I have sometimes problems with the feature "cluster". Now apt-dater is hanging with "Acquiring cluster locks".

How does the 'lock' mechanism work? Where can I find probably an 'lock' file to unlock again?

Regards
Thomas

**Comment by liske** [comment]
apt-dater uses a shell wrapper to run host commands: https://github.com/DE-IBH/apt-dater/blob/c43565e9bbee7b4cc65dd38d9916143b65bd8bee/lib/cmd#L93-L94

the lockfiles are inside the `stats-dir`
