### ISSUE TITLE
Unknown terminal: screen.xterm-256color

### ISSUE THREAD

**Issue by DejavuDmitry** [DE-IBH/apt-dater#156]
When I run `Midnight Commander`, `htop` or another ncurses-based application at remote host I get this error:
```
# mc                      
Unknown terminal: screen.xterm-256color
Check the TERM environment variable.
Also make sure that the terminal is defined in the terminfo database.
Alternatively, set the TERMCAP environment variable to the desired
termcap entry.
```
All I've changed was compiling current version from github.
Is this issue comes from `scren`?

**Comment by liske** [comment]
I don't think it's related to apt-dater. This is my default TERM (running Debian Buster):

```console
$ echo $TERM
xterm-256color
```
