### ISSUE TITLE
virtual machine detection inconsistent

### ISSUE THREAD

**Issue by nosilver4u** [DE-IBH/apt-dater#157]
I have a bunch of Digital Ocean machines managed with apt-dater, and for several of them, the 'v' flag does not show up. Running imvirt shows 'lguest' as the virtualization type, and 'apt-dater-host status' seems to pick this up, but the 'v' still doesn't show. Other hosts give the same results, and show the 'v' as expected. Even hosts that have been cloned directly from another show inconsistent results. Any idea why this could be?

Running apt-dater 1.0.3-4 on Debian 9, and apt-dater-host 1.0.0-4 on all the machines in question. Only the Debian 9 servers have this problem, a couple Debian 8 and Ubuntu 16.04 servers display the 'v' just fine.

**Comment by mathiashro** [comment]
Hello @nosilver4u, does is make sense to retest your reported issue as of now / with Debian 10?

**Comment by nosilver4u** [comment]
I actually just upgraded the apt-dater server to Debian 10 a couple weeks ago, and it seems to be working correctly. All the other servers are already using Debian 10 (or Ubuntu 16/18), so I think this is indeed resolved.

I'll keep an eye on it over the next couple weeks just to make sure.
