### ISSUE TITLE
Ubuntu 16.04 stock kernel detected as custom

### ISSUE THREAD

**Issue by nosilver4u** [DE-IBH/apt-dater#158]
On my Ubuntu 16.04 servers, the K flag is always shown, even though they are running stock kernels (currently 4.4.0-140-generic). Also, this seems to suppress the 'r' flag for rebooting, which perhaps is resolved in a newer version, but not sure about that.

Running apt-dater 1.0.3-4 on Debian 9, and apt-dater-host 1.0.0-4 on both Ubuntu 16.04 servers.

**Comment by nosilver4u** [comment]
I'm now running 1.0.4 on Debian 10 for the host, and have 1 Ubuntu 16.04 server and 1 Ubuntu 18.04 server that still show the K flag for a pending kernel upgrade, regardless of the kernel status.

**Comment by liske** [comment]
The kernel detection is done by https://github.com/liske/needrestart/ so this is not apt-dater related.

**Comment by nosilver4u** [comment]
Yeah, I think this was resolved at some point along the line, though I don't remember for sure. At this point, I'm running mostly Ubuntu servers with just a few Debian hosts, and do not have the issue currently. There are other quirks, but all clear on this one!
