### ISSUE TITLE
v1.0.4 is not installable

### ISSUE THREAD

**Issue by Commifreak** [DE-IBH/apt-dater#161]
As mentioned here: https://github.com/DE-IBH/apt-dater/pull/160#issuecomment-467347550 some files are now symlinks!

https://github.com/DE-IBH/apt-dater/tree/v1.0.4 ->

![unbenannt](https://user-images.githubusercontent.com/87267/53398741-ad866380-39aa-11e9-9341-17233d1584f6.JPG)

```
:# ./configure
configure: error: cannot find install-sh, install.sh, or shtool in "." "./.." "./../.."
```

**Comment by Commifreak** [comment]
Some more information: It seems, that the symlink behaviour is correct. But under Ubuntu 18.04, there is no automake 1.16, just 1.15.

How to handle that?

**Comment by liske** [comment]
The autotools stuff was broken and outdated, see also #180.
