### ISSUE TITLE
Debian 9 doesn't display current Kernel version in listing

### ISSUE THREAD

**Issue by Tyrewt** [DE-IBH/apt-dater#163]
Debian 9, upgraded from a past version, has the needrestart package (2.11-3+deb9u1) installed but doesn't display the Kernel version in the Apt-Dater listing.

Fresh installations of Debian 9 work with the same software versions.

- Debian 9.11
- apt-dater-host 1.0.0-4
- needrestart 2.11-3+deb9u1

**Comment by mathiashro** [comment]
Can you please review your other issue #164. My Debian "stretch" 9.13 is been reported as `<hostname> (Debian 9.13 stretch; 3.16.0-042stab145.3)`. Looks currently good for me.

**Comment by Tyrewt** [comment]
As shown, this issue and #164 both remain with Debian 9.12. Some machines correctly report the Kernel, others do not.

![apt-priv](https://user-images.githubusercontent.com/21961083/89935820-cb687800-dbe0-11ea-99a2-901852548dce.png)

**Comment by kosli** [comment]
@Tyrewt  I just had the same issue. You need to make sure that your "apt-dater" user is allowed (sudo) to run the` /usr/sbin/needrestart command`. This solved the issue for me, as I had forget to add that command in my sudoers file.

**Comment by Tyrewt** [comment]
> @Tyrewt I just had the same issue. You need to make sure that your "apt-dater" user is allowed (sudo) to run the` /usr/sbin/needrestart command`. This solved the issue for me, as I had forget to add that command in my sudoers file.

@kosli That was the culprit, not all hosts had that needrestart line, issue resolved. Thanks!
