### ISSUE TITLE
Debian 10 doesn't display current Kernel version in listing

### ISSUE THREAD

**Issue by Tyrewt** [DE-IBH/apt-dater#164]
Debian 10, upgraded from a past version, has the needrestart package (3.4-5) installed but doesn't display the Kernel version in the Apt-Dater listing.

Fresh installations of Debian 10 work with the same software versions.

- Debian 10.1
- apt-dater-host 1.0.1-1
- needrestart 3.4-5

**Comment by mathiashro** [comment]
Hello @Tyrewt, I can not confirm this behavior currently. I use as of now:
- Debian "buster" 10.4. 
- apt-dater-host 1.0.1-1 
- apt-dater 1.0.4
- needrestart 3.4-5

The output in apt-date is something like `<hostname> (Debian 10 buster; 4.19.0-9-amd64)`.

May be you can recheck and comment (or close) this issue?

**Comment by Tyrewt** [comment]
As shown, this issue and #163 both remain with Debian 10. Some machines correctly report the Kernel, others do not.

- Debian "buster" 10
- apt-dater-host 1.0.1-1
- apt-dater 1.0.3-4 (This server is Debian 9)
- needrestart 3.4-5

![apt-priv](https://user-images.githubusercontent.com/21961083/89936585-e25b9a00-dbe1-11ea-953f-117e73efcd6f.png)

**Comment by kosli** [comment]
@Tyrewt  I just had the same issue. You need to make sure that your "apt-dater" user is allowed (sudo) to run the` /usr/sbin/needrestart command`. This solved the issue for me, as I had forget to add that command in my sudoers file.

**Comment by Tyrewt** [comment]
> @Tyrewt I just had the same issue. You need to make sure that your "apt-dater" user is allowed (sudo) to run the` /usr/sbin/needrestart command`. This solved the issue for me, as I had forget to add that command in my sudoers file.

@kosli That was the culprit, not all hosts had that needrestart line, issue resolved. Thanks!
