### ISSUE TITLE
Does apt-dater refresh hosts automatically?

### ISSUE THREAD

**Issue by bd830dbd7432** [DE-IBH/apt-dater#167]
Greetings,

Couldn't find this information anywhere, so I hope this is the right place to ask.

If apt-dater is let open for days, does it refresh hosts (like pressing `g`) automatically?

If it does, is there any interval? Are hosts refreshed in random order and slowly to prevent overload in case of hundreds of servers, or everything together?

Thanks!

**Comment by mathiashro** [comment]
Hello @twouters, as from my practical knowledge there is not auto-refresh implemented. I do use `g` since years to refresh all hosts / host groups.

**Comment by liske** [comment]
Exactly, there is no regular refreshing.
