### ISSUE TITLE
DEBIAN_FRONTEND=noninteractive

### ISSUE THREAD

**Issue by le-zell** [DE-IBH/apt-dater#179]
Hello,

is it possible to push this option to the apt upgrade command in order to update debian os without taking all sessions one by one... ?

I have tried with no : 

- environments variables

but with no success. I haven't found apt-dater options to do that.

Thanks

**Comment by liske** [comment]
This should be configured on the target hosts IMHO.  One solution might be adding an option to `apt-dater-host` but it might also require some tuning for the wrapper used to become root.

Feel free to open the issue in apt-dater-host again.
