### ISSUE TITLE
apt-dater does not run on freebsd

### ISSUE THREAD

**Issue by enko** [DE-IBH/apt-dater#54]
I managed to compile and install apt-dater on freebsd, but when running a refresh on a host I get this error in the diagnostic:

    Pseudo-terminal will not be allocated because stdin is not a terminal.
    Host key verification failed. 

Also when I try to connect to the host I get this error:

    grep: The -P option is not supported
    === Command terminated normally (Sun Nov  9 14:14:13 2014) ===

This seems to stem from the fact that bsdgrep does not support PCRE regexes.

**Comment by liske** [comment]
The libconfig stuff has been dropped in HEAD. apt-dater 1.0.2 will use XML config files parsed by libxml and should not contain any of the regressions of this issue any more.
