### ISSUE TITLE
optional serial command execution per host group

### ISSUE THREAD

**Issue by lpirl** [DE-IBH/apt-dater#55]
I have systems with multiple virtualized containers. Those containers share an apt cache. Hence, they can't be refreshed nor updated in parallel. I'd love to see a configuration symbol for host groups that makes apt-dater issue all it's commands in serial.
Thanks for apt-dater!

**Comment by ktosiek** [comment]
Clusters help with upgrade, but they don't affect refresh. With multiple LXC containers on the same host it can really affect the host's performance.

**Comment by lpirl** [comment]
This issue is not relevant for me anymore (using Ansible all the way). Feel free to close the issue.
