### ISSUE TITLE
sporadic segfault

### ISSUE THREAD

**Issue by dkadioglu** [DE-IBH/apt-dater#58]
I'm using apt-dater on Arch Linux without any testing packages. Sporadically apt-dater segfaults and I cannot reproduce it. Here is the backtrace: http://pastebin.com/bFiT74Uc

If you need further information, please ask.

**Comment by dkadioglu** [comment]
This seems to be fixed now with the most recent code, at least there were no such crashes since days of usage. Maybe that's connected with the recent switch to XML-based configuration files?

**Comment by liske** [comment]
I think it was triggered by a broken integration of libconfig... so this issue could be closed.
