### ISSUE TITLE
custom limit on simultaneous jobs.

### ISSUE THREAD

**Issue by kiranos** [DE-IBH/apt-dater#60]
I manged around 300 servers and it would be great to be able to run 25-50 screens simultaneously, now it seems to stop at around 13 or so. Is there a way to set another limit ?

**Comment by liske** [comment]
This sounds strange... I'd just upgraded 80+ hosts simultaneously (read: 80 concurrent screen sessions).

**Comment by kiranos** [comment]
hm strange I dont know how to debug this though I've tried again and it just doesnt trigger more than 13 simulanious

**Comment by kiranos** [comment]
I can now close this, it was an error on my part, I hosted the apt-dater server on an openvz container which has a limit on how many phy connections you can make.
