### ISSUE TITLE
Question: Upgrade doesn't work, no information given why

### ISSUE THREAD

**Issue by felicitus** [DE-IBH/apt-dater#66]
Hi,

I just setup apt-dater to update several hosts. Those hosts are shown in the "Updates pending" section. When I hit "u", the particular host moves into the "Refresh required", then "In refresh" section and then back to the "Updates pending" section, with no updates applied.

Is there any way to check a log of what's going wrong at that point?

My version of apt-dater is 0.9.0.

Thanks
Felicitus

**Comment by liske** [comment]
Hi Felicitus,

this sounds strange... since the hosts are listed in "Updates pending" the SSH access seems to be working somehow. Could you please try to run a `ssh $HOSTNAME apt-dater-host upgrade` from your management station?

HTH,
Thomas

**Comment by felicitus** [comment]
I just found the issue - I forgot to copy the screenrc. Probably apt-dater should check if the screenrc file it tries to use exists on startup.
