### ISSUE TITLE
filename convention of releases

### ISSUE THREAD

**Issue by hoehnp** [DE-IBH/apt-dater#69]
Thank you for your great work. 

I am currently trying to create a gentoo package of apt-dater. With the stable version 0.9.0 I have trouble as another package already uses a file with the exactly same name. Right now I resolved the problem by forking your repository and renaming the release in my fork. However, I would prefer to use your upstream releases directly. Beside this problem, I would suggest it to be, in general, useful to use a more unique file name, e.g. when having many downloads in one folder, it could be easier identified in this case. I may suggest for example apt-dater-v0.9.0.zip.

**Comment by liske** [comment]
The archive downloads are provided by github automatically. It is not possible to change the archive filename format, it always uses the tag name AFAIK.
