### ISSUE TITLE
Cannot connect or upgrade any host.

### ISSUE THREAD

**Issue by valentin-fischer** [DE-IBH/apt-dater#70]
Hi,
I'm using the debian version 
ii  apt-dater                                                   0.9.0-7                                             amd64        terminal-based remote package update manager
ii  apt-dater-host                                              0.9.0-7                                             all          host helper application for apt-dater

The problem is that I cannot connect to any host or do any upgrade. 

I just get the following messages and nothing happens...
Script started, file is /home/valentin/.local/share/apt-dater/history/backup.xx.xx:22/1427702492-32112/typescript
Script done, file is /home/valentin/.local/share/apt-dater/history/backup.xx.xx:22/1427702492-32112/typescript
=== Command terminated normally (Mon Mar 30 10:01:32 2015) ===

**Comment by liske** [comment]
Hi,

do you have any special options in your apt-dater.conf set? Are you able to login to the remote host on the CLI (`ssh -p 22 backup.xx.xx` and `ssh -p 22 backup.xx.xx apt-dater-host refresh`)?

HTH,
Thomas

**Comment by valentinul** [comment]
Nothing added in my config, I can connect without any issues to the host.

**Comment by kallies** [comment]
@valentinul is this still an issue?
