### ISSUE TITLE
stability of 1.x

### ISSUE THREAD

**Issue by dunn** [DE-IBH/apt-dater#71]
Should 1.0.0 and/or 1.0.1 be considered stable?  0.9.0 is still listed as the latest release; subsequent tags are "Pre-releases".

**Comment by liske** [comment]
1.0.x releases are not stable. Although switching the config file backend from glib keyfiles to libxml is almost done I'm going to switch from screen to tmux. I'm aware of some stability issues in 1.0.x/git head - you should keep on 0.9.0.

**Comment by dunn** [comment]
Thanks!
