### ISSUE TITLE
[CRITICAL] apt-dater removes conflicting packages without warning 

### ISSUE THREAD

**Issue by mc0e** [DE-IBH/apt-dater#72]
I use mariadb, sourced from mariadb's own apt repository.  This overrides some of the mysql packages from debian.

apt-dater points out that libmysqlclient18 has a security update available.  I currently have 5.5.42+maria-1~wheezy, and 5.5.43-0+deb7u1 is available from wheezy-security.

apt-dater doesn't point out though that the newer libmysqlclient18 is not compatible with my current version of libmariadbclient18 (and a later one is not yet available).  If I let apt-dater update libmysqlclient18 it uninstalls libmariadbclient18 and mariadb's client and server packages, while giving no hint of a problem, which is obviously disastrous.

I view apt-dater as unsafe to use until this is fixed.  Even if it can't resolve the situation, it needs appropriate warnings.

**Comment by helmo** [comment]
This is #28 biting again ... It should be fixed, but not in the version shipped with Wheezy.

**Comment by helmo** [comment]
The version in Jessie and wheezy-backports has this update. Note that it just adds a confirmation, a removal is not shown before starting an upgrade session :(

After adding the backports source you need to ```apt-get install -t wheezy-backports apt-dater-host``` on any affected host.

**Comment by liske** [comment]
Please don't blame apt-get frontends like apt-dater-host for broken mariadb repositories. The enhancement in #28 requires the user to manual review the packages to be removed so I would not consider apt-dater to be unsafe.

**Comment by mc0e** [comment]
The problem is with apt-dater.  Yes, there is an issue with the mariadb repository, but there are other ways for conflicts to arise, and it's up to apt-dater to show appropriate caution and allow the user to decide what to do.  This remains a critical issue, which makes apt-dater unsafe to use.

The problem is that apt-dater-host is using a `dist-upgrade` operation which is intended for upgrading the version of the whole operating system.  It should be using `upgrade`.

This ticket should not have been closed.

**Comment by liske** [comment]
`dist-upgrade` is essentials to get security upgrades with ABI changes (like linux-images, bind's stub resolver etc.).

**Comment by mc0e** [comment]
I disagree strongly.  I'll keep my fork of apt-dater-host open and use that.

On my pull request you say there's a config option for this.  It was not obvious from my admittedly quick look over the man page and the code.  Where is this option?
