### ISSUE TITLE
[RFE] converting old config files

### ISSUE THREAD

**Issue by atrent** [DE-IBH/apt-dater#73]
Hi, is there a script to convert old config files into XML?
(I have many hosts...)
Thanks

**Comment by liske** [comment]
apt-dater contains a script to convert the old hosts.conf into the new hosts.xml format (8d50d62063fd001e8dedbb6fea7cdb43e6256d96). The script is called `hosts2xml` and will be called by apt-dater if you don't have a `hosts.xml` but a `hosts.conf` file.
