### ISSUE TITLE
tries to resolve ssh name

### ISSUE THREAD

**Issue by tpo** [DE-IBH/apt-dater#76]
The hosts I'm connecting to are somewhat complicated to reach, i.e. over jump hosts etc.

All of this is configured in ~/.ssh/config.

But it seems that when I use the host names ~/.ssh/config, apt-updater will not be able to connect to the hosts.

Is there a way for apt-updater to respect ~/.ssh/config when connecting to hosts?

I've tested with v1.0.1 and 0.9.

**Comment by tpo** [comment]
no, after tracing apt-dater, I see that it actually does connect, but still, the host remains in the "Unknown" state. I'll have to investigate further...

**Comment by tpo** [comment]
So when I run apt-dater 1.0.1 and look at the diagonstics I see:

    ssh: Could not resolve hostname (null): Name or service not known

But when I execute the command manually, that I see apt-dater executing in the strace...

    [pid 26109] execve("/usr/bin/ssh", ["/usr/bin/ssh", "(null)", "-n", "-o", "BatchMode=yes", "-o", "ConnectTimeout=5", "myhost", "apt-dater-host", "refresh"], [/* 87 vars */]) = 0

thus:

    /usr/bin/ssh -n -o BatchMode=yes -o ConnectTimeout=5 myhost apt-dater-host refresh

then it works.

I am stomped.
*t

**Comment by tpo** [comment]
OK, updating from Debian's experimental to the github version fixed everything.

Thanks!

**Comment by liske** [comment]
Hi,

sadly apt-dater in sid is very buggy. Due to the jessie freeze there was a upload to experimental fix some bugs - but both version are still unstable.

HTH,
Thomas
