### ISSUE TITLE
"failure diagnostic" can't use environnement variables

### ISSUE THREAD

**Issue by fufroma** [DE-IBH/apt-dater#77]
Hello,

My apt-dater configuration is in a git repository. I want to have a specific ssh configuration file for apt-dater.

So, in my apt-dater.xml : 
`<ssh opt-cmd-flags="-F $HOME/.config/apt-dater/ssh_config -t"/>`

(yes, my home can change so I use a var)

It work perfectly for connection, refresh... but the failure diagnostic show an error : 
`FAILURE DIAGNOSTIC`
`Can't open user config file $HOME/.config/apt-dater/ssh_config: No such file or directory`

I tried using ~ instead on $HOME, but the connection does not work with this configuration.

Version : 
apt-dater                             1.0.1+git20150119-1

Best regards,

**Comment by liske** [comment]
Which operations are failing? apt-dater calls a wrapper shell script at `/usr/lib/x86_64-linux-gnu/apt-dater/cmd` to run the operation on the host. Maybe you could add a `-x` into the shell script to debug your problem. I've never tried to use environment variables... but all operations should behave the some.

**Comment by fufroma** [comment]
The remote command works fine.

It's the "failure diagnostic" tools who doesn't work, and fail on the error I gave previously.

**Comment by fufroma** [comment]
Found it :)

The $VARS aren't expanded when executed. I have to manually expand them before.

In /usr/lib/i386-linux-gnu/apt-dater/cmd I add an explicit expand : 
AD_SSH_OPTFLAGS="$(eval echo $AD_SSH_OPTFLAGS)"
 
It expand the vars of the string. But it's quite insecure.

I do not see other way to allow use of env vars in the script, and to be complete it should expand many other vars too (hooks directory, etc...).

Maybe a WONTFIX will be the safest way to go.

**Comment by liske** [comment]
Maybe there should be the possibility to replace environment variables with-in apt-dater before calling `cmd`. As a workaround you could set your plugin type to a selfmade script (see also at https://www.ibh.de/talks/2015/CLT/201503-CLT_apt-dater.html#/step-31 in German, but the sketches/screenshots should be self-explaining).
