### ISSUE TITLE
update command very often terminating with "Write failed: Broken pipe"

### ISSUE THREAD

**Issue by tpo** [DE-IBH/apt-dater#80]
When doing updates with apt-dater 1.0.2 I very often get:

```
...
Setting up libpq5 (9.1.16-0+deb7u1) ...
localepurge: Disk space freed in /usr/share/locale: 288 KiB
localepurge: Disk space freed in /usr/share/man: 0 KiB

Total disk space freed by localepurge: 288 KiB

Shared connection to 192.168.138.53 closed.
Write failed: Broken pipe
Script done, file is /var/lib/apt-dater/history/myhost:0/1432629471-25129/typescript
=== Command terminated normally (Tue May 26 10:38:14 2015) ===
```

and when I press 'q' to continue:

```
Ein Fehler bei myhost wurde gefunden [Less/ignore/connect]: 
```

I am unable to say when this happens. Sometimes upgrading works without the "Broken pipe" and sometimes not. ATM I can't see any correlation.

?
*t

**Comment by liske** [comment]
Hi,

did you observe simular issues during ssh sessions w/o apt-dater? The error might be triggered by ssh itself (unstable connection, missing tcp keepalive & stateful firewall, ...).

**Comment by tpo** [comment]
On Sun, 21 Jun 2015, Thomas Liske wrote:

> did you observe simular issues during ssh sessions w/o apt-dater? The 
> error might be triggered by ssh itself (unstable connection, missing tcp
> keepalive & stateful firewall, ...).

No, ssh by itself works fine (just as it does when used by ansible).

However, your comment prompted me to suspect that configuring ssh with 
"persistent connections":

     $ cat ~/.ssh/config
     ...
     Host *
       ControlPath ~/.ssh/master-%l-%r@%h:%p
       ControlMaster auto
       ControlPersist 10

could have something to do with it. So I commented the "persistent 
ssh connections" out and haven't seen the "Write failed: Broken pipe" 
error since.

So maybe you could have a look at apt-dater behavior when ssh is 
configured to keep connections persistent?
*t

**Comment by liske** [comment]
If think the *Broken pipe* messages are triggered by a premature terminated master connections (the first remote login of a host) killing any pending sessions.

**Comment by tpo** [comment]
On Mon, 22 Jun 2015, Thomas Liske wrote:

> If think the Broken pipe messages are triggered by a premature terminated master connections (the first remote login of a host) killing any pending
> sessions.

Why would that be happening though only during apt-dater operation? Is 
there something that is inducing this weird behavior? I am not ever 
experiencing this otherwise (normal ssh usage as sysadmin or when 
deploying stuff/machines/changes via ansible).

Maybe the way apt-dater is setting up the terminal or something else is 
incomprehensible to ssh, so the ssh executable thinks there is no 
connected terminal and will close it too early? Maybe something in the way 
the terminal session is teared down? Maybe the sequence of closing the 
ssh/terminal filedescriptors (STDIN then STDOUT then STDERR or something) 
is not fine with ssh?

The (interactive apt-dater ssh) session allways runs through here. All 
actions that apt-dater needs to do are allways executed 'till the end. 
It's only at the very end that "Broken pipe" occurs/gets displayed.

Hmmm...
*t

**Comment by liske** [comment]
The terminal should be fine. apt-dater runs:
- `screen` (or `tmux`) to make the session detachable
- inside `script` is used to record the session
- `script` runs the ordinary `ssh` command

How do you start the master connection (`ssh -M`)?

**Comment by tpo** [comment]
On Sun, 5 Jul 2015, Thomas Liske wrote:

> The terminal should be fine. apt-dater runs:
>
>  *  screen (or tmux) to make the session detachable
>  *  inside script is used to record the session
>  *  script runs the ordinary ssh command
> 
> How do you start the master connection (ssh -M)?

I do not start the master connection at all. It is started implicitly 
when I do a ssh target (or, respectively when apt-dater connects to a 
target).
*t

**Comment by liske** [comment]
I am closing this rather old issue whose cause is probably not in apt-dater.

**Comment by tpo** [comment]
> I am closing this rather old issue whose cause is probably not in apt-dater.

I don't know where the problem lies in, however haven't been bothered by that problem lately, so ... fair enough. Thanks for the bug triage @liske !
