### ISSUE TITLE
Upgrade more than one host doesn't work with tmux

### ISSUE THREAD

**Issue by dkadioglu** [DE-IBH/apt-dater#84]
Hi,

I've compiled the latest git checkout with tmux and upgrading more than one host at once is not possbile anymore. If I upgrade a group of hosts I see console output giving me usage hints for tmux. It seems that the call of the tmux command is somehow wrong.

If you need more details, please ask.

**Comment by liske** [comment]
Hi,

tmux was called using the `-d` option at a wrong position while creating a new *detached* session. The commit 027a2f3 had fixed this regression.


Thanks & HTH,
Thomas
