### ISSUE TITLE
refresh hosts doesn't work anymore

### ISSUE THREAD

**Issue by dkadioglu** [DE-IBH/apt-dater#87]
Hi,

thanks for the fast fix of #84!
Now I've got the problem that nothing happens when I refresh one or more hosts. All of them are moved to the group "Aktualisierung benötigt" and that's it. If I want to close apt-dater I see the message "Es werden 9 Hosts aktualisiert, Apt-Dater beenden?" but there is no running tmux process.
Sorry for the german message texts. If you need further information, please ask.

Thanks

**Comment by liske** [comment]
apt-dater is currently undergoing some extended modifications in preperation of the next upcoming pre-release. You did just fetch a non-ready snapshot of git HEAD. I've just merged #88 - this should fix most issues including the hangig refreshes. Thanks for your feedback!

HTH,
Thomas
