### ISSUE TITLE
After an upgrade has finished the session is not killed but I see Pane is dead

### ISSUE THREAD

**Issue by dkadioglu** [DE-IBH/apt-dater#90]
Hi,

I know that apt-dater is undergoing many changes at the moment but, here is another one:
When I upgrade hosts the corrsponding sessions are never closed. Instead I can look at one of them by pressing a and below the console output I can see the message Pane is dead. The problem is that I can't leave the session and I can't do anything else, apt-dater just hangs.
If you need further information, please ask.

**Comment by kiranos** [comment]
which version are you using?

**Comment by dkadioglu** [comment]
The most recent git checkout.

**Comment by liske** [comment]
tmux does not terminate if the command inside tmux has exited automaticly (same way it is using the screen backend). You need to kill the pane using `C-a x`.

**Comment by dkadioglu** [comment]
Thanks for that clue, I wasn't aware of that. I think with screen it was just pressing q (at least it is that what I can remember...).
One question: would there be any side effects if I put "set -g set-remain-on-exit off" in tmux.conf?

**Comment by liske** [comment]
Sadly tmux requires you to press the prefix followed by `x`. You are right, in screen you just need to hit `q` - and screen does tell you about it. Tmux doesn't give you any hint howto kill the terminated session.

If you disable the `set-remain-on-exit` option the session will just close after any upgrades (if there is nothing during the upgrade requiring you to press a key).
